//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT027945:"HR SAGE SALARY PAYMENT",FLT027946:"Upload File",FLT027948:"Select",FLT027949:"Upload",
FLT027952:"Generate File",FLT031451:"Delete",FLT027947:"Function Code",FLT027950:"Inquire",
FLT1030546:"Submit",
FLT1030509:"Cancel",
FLT1030510:"Go",
FLT1030511:"Clear",
FLT1030519:"Show Input",
FLT1030520:"Upload"
};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
